package routes

import (
	"github.com/gin-gonic/gin"
	"rentflow-api/controllers"
	"rentflow-api/middleware"
)

func RegisterRentFlowRoutes(r *gin.Engine) {
	r.Use(middleware.AttachRentFlowSession())

	r.POST("/auth/google", controllers.RentFlowAuthWithGoogle)
	r.POST("/auth/register", controllers.RentFlowRegister)
	r.POST("/auth/login", controllers.RentFlowLogin)
	r.GET("/auth/me", controllers.RentFlowGetMe)
	r.POST("/auth/logout", controllers.RentFlowLogout)
	r.GET("/tenants/resolve", controllers.RentFlowResolveTenant)

	r.GET("/cars", controllers.RentFlowGetCars)
	r.GET("/cars/:carId/image", controllers.RentFlowGetCarPrimaryImage)
	r.GET("/cars/:carId/images/:imageId", controllers.RentFlowGetCarImage)
	r.GET("/branches", controllers.RentFlowGetBranches)
	r.GET("/branches/:branchId", controllers.RentFlowGetBranchByID)
	r.POST("/webhooks/line/:tenantSlug", controllers.RentFlowLineWebhook)
	r.POST("/availability/check", controllers.RentFlowCheckAvailability)
	r.GET("/availability/:carId/unavailable-dates", controllers.RentFlowGetUnavailableDates)

	r.POST("/bookings/preview", controllers.RentFlowPreviewBookingPrice)
	r.POST("/bookings", controllers.RentFlowCreateBooking)
	r.POST("/payments", controllers.RentFlowCreatePayment)
	r.GET("/payments/booking/:bookingId", controllers.RentFlowGetPaymentByBookingID)
	r.GET("/reviews", controllers.RentFlowGetReviews)
	r.POST("/reviews", controllers.RentFlowCreateReview)
	r.POST("/ai/storefront-assistant", controllers.RentFlowStorefrontAssistant)

	protected := r.Group("/")
	protected.Use(middleware.RequireRentFlowSession())
	{
		protected.GET("/users/me", controllers.RentFlowUserMe)
		protected.PATCH("/users/me", controllers.RentFlowUpdateMe)
		protected.PATCH("/users/me/password", controllers.RentFlowChangePassword)

		protected.GET("/tenants/me", controllers.RentFlowGetMyTenant)
		protected.POST("/tenants/me", controllers.RentFlowUpsertMyTenant)
		protected.PUT("/tenants/me", controllers.RentFlowUpsertMyTenant)

		protected.GET("/partner/dashboard", controllers.RentFlowPartnerDashboard)
		protected.GET("/partner/ai/assistant", controllers.RentFlowPartnerAssistant)
		protected.GET("/partner/reports", controllers.RentFlowPartnerGetReports)
		protected.GET("/partner/cars", controllers.RentFlowPartnerGetCars)
		protected.POST("/partner/cars", controllers.RentFlowPartnerCreateCar)
		protected.PATCH("/partner/cars/:carId", controllers.RentFlowPartnerUpdateCar)
		protected.DELETE("/partner/cars/:carId", controllers.RentFlowPartnerDeleteCar)
		protected.POST("/partner/cars/:carId/images", controllers.RentFlowUploadCarImages)
		protected.PATCH("/partner/cars/:carId/images/reorder", controllers.RentFlowPartnerReorderCarImages)
		protected.DELETE("/partner/cars/:carId/images/:imageId", controllers.RentFlowPartnerDeleteCarImage)
		protected.GET("/partner/branches", controllers.RentFlowPartnerGetBranches)
		protected.POST("/partner/branches", controllers.RentFlowPartnerCreateBranch)
		protected.PATCH("/partner/branches/:branchId", controllers.RentFlowPartnerUpdateBranch)
		protected.DELETE("/partner/branches/:branchId", controllers.RentFlowPartnerDeleteBranch)
		protected.GET("/partner/bookings", controllers.RentFlowPartnerGetBookings)
		protected.PATCH("/partner/bookings/:bookingId/status", controllers.RentFlowPartnerUpdateBookingStatus)
		protected.GET("/partner/payments", controllers.RentFlowPartnerGetPayments)
		protected.PATCH("/partner/payments/:paymentId/verify", controllers.RentFlowPartnerVerifyPayment)
		protected.PATCH("/partner/payments/:paymentId/refund", controllers.RentFlowPartnerRefundPayment)
		protected.PATCH("/partner/payments/:paymentId/settle", controllers.RentFlowPartnerSettlePayment)
		protected.GET("/partner/customers", controllers.RentFlowPartnerGetCustomers)
		protected.GET("/partner/calendar", controllers.RentFlowPartnerGetCalendar)
		protected.POST("/partner/availability-blocks", controllers.RentFlowPartnerCreateAvailabilityBlock)
		protected.DELETE("/partner/availability-blocks/:blockId", controllers.RentFlowPartnerDeleteAvailabilityBlock)
		protected.GET("/partner/promotions", controllers.RentFlowPartnerListPromotions)
		protected.POST("/partner/promotions", controllers.RentFlowPartnerCreatePromotion)
		protected.PATCH("/partner/promotions/:promotionId", controllers.RentFlowPartnerUpdatePromotion)
		protected.DELETE("/partner/promotions/:promotionId", controllers.RentFlowPartnerDeletePromotion)
		protected.GET("/partner/addons", controllers.RentFlowPartnerListAddons)
		protected.POST("/partner/addons", controllers.RentFlowPartnerCreateAddon)
		protected.PATCH("/partner/addons/:addonId", controllers.RentFlowPartnerUpdateAddon)
		protected.DELETE("/partner/addons/:addonId", controllers.RentFlowPartnerDeleteAddon)
		protected.GET("/partner/leads", controllers.RentFlowPartnerListLeads)
		protected.POST("/partner/leads", controllers.RentFlowPartnerCreateLead)
		protected.PATCH("/partner/leads/:leadId", controllers.RentFlowPartnerUpdateLead)
		protected.DELETE("/partner/leads/:leadId", controllers.RentFlowPartnerDeleteLead)
		protected.GET("/partner/members", controllers.RentFlowPartnerListMembers)
		protected.POST("/partner/members", controllers.RentFlowPartnerCreateMember)
		protected.PATCH("/partner/members/:memberId", controllers.RentFlowPartnerUpdateMember)
		protected.DELETE("/partner/members/:memberId", controllers.RentFlowPartnerDeleteMember)
		protected.GET("/partner/domains", controllers.RentFlowPartnerListDomains)
		protected.POST("/partner/domains", controllers.RentFlowPartnerCreateDomain)
		protected.PATCH("/partner/domains/:domainId/verify", controllers.RentFlowPartnerVerifyDomain)
		protected.DELETE("/partner/domains/:domainId", controllers.RentFlowPartnerDeleteDomain)
		protected.GET("/partner/messaging/line", controllers.RentFlowPartnerGetLineMessaging)
		protected.POST("/partner/messaging/line", controllers.RentFlowPartnerSaveLineMessaging)
		protected.POST("/partner/messaging/line/test", controllers.RentFlowPartnerTestLineMessaging)
		protected.POST("/partner/messaging/line/webhook/test", controllers.RentFlowPartnerTestLineWebhook)
		protected.DELETE("/partner/messaging/line", controllers.RentFlowPartnerDeleteLineMessaging)
		protected.GET("/partner/support", controllers.RentFlowPartnerGetSupport)
		protected.PATCH("/partner/support/tickets/:ticketId", controllers.RentFlowPartnerUpdateSupportTicket)
		protected.POST("/partner/support/tickets/:ticketId/messages", controllers.RentFlowPartnerCreateSupportMessage)
		protected.GET("/partner/audit-logs", controllers.RentFlowPartnerGetAuditLogs)
		protected.GET("/platform/me", controllers.RentFlowAdminGetMe)
		protected.GET("/platform/ai/assistant", controllers.RentFlowAdminAssistant)
		protected.GET("/platform/overview", controllers.RentFlowAdminGetOverview)
		protected.GET("/platform/partners", controllers.RentFlowAdminListPartners)
		protected.GET("/platform/domains", controllers.RentFlowAdminListDomains)
		protected.GET("/platform/billing", controllers.RentFlowAdminGetBilling)
		protected.GET("/platform/security", controllers.RentFlowAdminGetSecurity)
		protected.GET("/platform/tenants", controllers.RentFlowAdminListTenants)
		protected.PATCH("/platform/tenants/:tenantId/status", controllers.RentFlowAdminUpdateTenantStatus)

		protected.GET("/bookings/me", controllers.RentFlowGetMyBookings)
		protected.GET("/bookings/:bookingId", controllers.RentFlowGetBookingByID)
		protected.PATCH("/bookings/:bookingId/cancel", controllers.RentFlowCancelBooking)

		protected.POST("/cars/:carId/images", controllers.RentFlowUploadCarImages)

		protected.GET("/notifications", controllers.RentFlowGetNotifications)
		protected.PATCH("/notifications/:notificationId/read", controllers.RentFlowMarkNotificationAsRead)
		protected.PATCH("/notifications/read-all", controllers.RentFlowMarkAllNotificationsAsRead)
	}
}
